### ISSUE TITLE
Mongoose 5 Compatibility

### ISSUE THREAD

**Issue by mamsoudi** [sharvit/mongoose-data-seed#11]
Hey there, Thanks for the extension.
Just wanted to inform you that I get this warning each time I run `md-seed run` and it's pretty obvious what it says. Maybe you could check mongoose version to see whether `useMongoClient` should be used or not. Oh and seeding still works though.

Here's the full error anyway:
```
WARNING: The `useMongoClient` option is no longer necessary in mongoose 5.x, please remove it.
    at handleUseMongoClient (/Users/masoud/Desktop/Work/peeker/proshat-workflows/node_modules/mongoose/lib/connection.js:506:17)
    at NativeConnection.Connection.openUri (/Users/masoud/Desktop/Work/peeker/proshat-workflows/node_modules/mongoose/lib/connection.js:407:7)
    at Mongoose.connect (/Users/masoud/Desktop/Work/peeker/proshat-workflows/node_modules/mongoose/lib/index.js:208:15)
    at /Users/masoud/.nvm/versions/node/v8.9.2/lib/node_modules/mongoose-data-seed/dist/bin/run/index.js:75:14
    at new Promise (<anonymous>)
    at run (/Users/masoud/.nvm/versions/node/v8.9.2/lib/node_modules/mongoose-data-seed/dist/bin/run/index.js:73:10)
    at exports.default (/Users/masoud/.nvm/versions/node/v8.9.2/lib/node_modules/mongoose-data-seed/dist/bin/run/index.js:24:10)
    at Object.<anonymous> (/Users/masoud/.nvm/versions/node/v8.9.2/lib/node_modules/mongoose-data-seed/dist/bin/index.js:55:27)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3```

**Comment by sharvit** [comment]
Thanks for filling that issue @mamsoudi 👍 

It's basically about this line:
https://github.com/sharvit/mongoose-data-seed/blob/master/src/bin/run/index.js#L39

I agree it's a good idea to check for the current mongo version before creating the connection.

I think I can work on that this weekend.
PR are more than welcome 🥇 🙏
