### ISSUE TITLE
Run command returns TypeError: Seeder is not a constructor

### ISSUE THREAD

**Issue by antonkomarev** [sharvit/mongoose-data-seed#45]
I'm trying to run `$ md-seed run` command, but receive TypeError:

> TypeError: Seeder is not a constructor

## I'm submitting a…

* [ ] Regression (a behavior that used to work and stopped working in a new release)
* [ ] Bug report 
* [ ] Feature request
* [ ] Documentation issue or request
* [x] Support request

## Expected Behavior

Seeder executed successfully.

## Current Behavior

```
$ md-seed run

✔ Successfully connected to MongoDB!

Seeding Results:
✖ CountriesSeeder
TypeError: Seeder is not a constructor
    at MdSeedRunner._runSeeder (/home/test-app/node_modules/mongoose-data-seed/dist/lib/core/md-seed-runner.js:192:22)
    at MdSeedRunner._runSeeders (/home/test-app/node_modules/mongoose-data-seed/dist/lib/core/md-seed-runner.js:161:18)
    at MdSeedRunner._run (/home/test-app/node_modules/mongoose-data-seed/dist/lib/core/md-seed-runner.js:76:18)
    at process.internalTickCallback (internal/process/next_tick.js:77:7)
```

## Environment

* mongoose-data-seed version: 2.1.3
* Node version: v11.6.0
* Yarn version: 1.17.3
* Operating system: Linux

**Comment by antonkomarev** [comment]
This issue could be related to this comment: https://github.com/sharvit/mongoose-data-seed/issues/8#issuecomment-379190507

**Comment by sharvit** [comment]
Thank you for submitting an issue @antonkomarev 

Any chance you can supply an environment/repository that showcases the issue?
It might help in this case so I can reproduce the error.

Some directions you can try:
1. Upgrading to node-12 (AFAIK node-11 is not stable)
2. Try downgrading `mongoose-data-seed version` to version `2.1.1` or `2.0.1`, it might give us a clue if we the new version is broke.

Thanks

**Comment by antonkomarev** [comment]
I've tried to downgrade to `2.1.1` & `2.0.1` but no luck, issue is in place.

The only difference in error output in `2.0.1`:
```
TypeError: Seeder is not a constructor
    at MdSeedRunner._callee5$ (/home/test-app/node_modules/mongoose-data-seed/dist/lib/core/md-seed-runner.js:334:26)
    at tryCatch (/home/test-app/node_modules/regenerator-runtime/runtime.js:45:40)
    at Generator.invoke [as _invoke] (/home/test-app/node_modules/regenerator-runtime/runtime.js:271:22)
    at Generator.prototype.(anonymous function) [as next] (/home/test-app/node_modules/regenerator-runtime/runtime.js:97:21)
    at asyncGeneratorStep (/home/test-app/node_modules/mongoose-data-seed/dist/lib/core/md-seed-runner.js:24:103)
    at _next (/home/test-app/node_modules/mongoose-data-seed/dist/lib/core/md-seed-runner.js:26:194)
    at /home/test-app/node_modules/mongoose-data-seed/dist/lib/core/md-seed-runner.js:26:364
    at new Promise (<anonymous>)
    at MdSeedRunner.<anonymous> (/home/test-app/node_modules/mongoose-data-seed/dist/lib/core/md-seed-runner.js:26:97)
    at MdSeedRunner._runSeeder (/home/test-app/node_modules/mongoose-data-seed/dist/lib/core/md-seed-runner.js:370:28)
    at MdSeedRunner._callee4$ (/home/test-app/node_modules/mongoose-data-seed/dist/lib/core/md-seed-runner.js:281:29)
    at tryCatch (/home/test-app/node_modules/regenerator-runtime/runtime.js:45:40)
    at Generator.invoke [as _invoke] (/home/test-app/node_modules/regenerator-runtime/runtime.js:271:22)
    at Generator.prototype.(anonymous function) [as next] (/home/test-app/node_modules/regenerator-runtime/runtime.js:97:21)
    at asyncGeneratorStep (/home/test-app/node_modules/mongoose-data-seed/dist/lib/core/md-seed-runner.js:24:103)
    at _next (/home/test-app/node_modules/mongoose-data-seed/dist/lib/core/md-seed-runner.js:26:194)
```

Repository where I'm trying to start using your package is proprietary, so I can't share it, but will try to create sandbox if there will be no solution found.

**Comment by antonkomarev** [comment]
Upgrade node to `v12.8.1` didn't help too.

**Comment by antonkomarev** [comment]
I've added plugin:
```json
"plugins": [
  "add-module-exports"
]
```

Issue replaced with another one:
> TypeError: Class constructor Seeder cannot be invoked without 'new'

I've modified preset and everything seems to work now:
```json
{
  "presets": [
    [
      "@babel/preset-env",
      {
        "targets": {
          "node": 8
        }
      }
    ]
  ],
  "plugins": [
    "add-module-exports"
  ]
}
```

Thank for the help @sharvit!

I don't understand difference between `@babel/preset-env` & `@babel/env`, but first one works in my case.
